// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO7-INO9EtKhPXCCzxVJ6uQBov9xUfA-g',
    appId: '1:762442800435:web:1a4fdd11d99e0dd3d5f246',
    messagingSenderId: '762442800435',
    projectId: 'inventory-ezzy',
    authDomain: 'inventory-ezzy.firebaseapp.com',
    storageBucket: 'inventory-ezzy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQLpFE6GB9f_lbgoSx4MlK6V1sXV3xtI',
    appId: '1:762442800435:android:9fe13b354e47866dd5f246',
    messagingSenderId: '762442800435',
    projectId: 'inventory-ezzy',
    storageBucket: 'inventory-ezzy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCENFmCHCi1pbMiQMzCmWTVnILKXdriKvk',
    appId: '1:762442800435:ios:3cf8f4f6c1580c70d5f246',
    messagingSenderId: '762442800435',
    projectId: 'inventory-ezzy',
    storageBucket: 'inventory-ezzy.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCENFmCHCi1pbMiQMzCmWTVnILKXdriKvk',
    appId: '1:762442800435:ios:3cf8f4f6c1580c70d5f246',
    messagingSenderId: '762442800435',
    projectId: 'inventory-ezzy',
    storageBucket: 'inventory-ezzy.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO7-INO9EtKhPXCCzxVJ6uQBov9xUfA-g',
    appId: '1:762442800435:web:7afdd8fd875dc07ed5f246',
    messagingSenderId: '762442800435',
    projectId: 'inventory-ezzy',
    authDomain: 'inventory-ezzy.firebaseapp.com',
    storageBucket: 'inventory-ezzy.firebasestorage.app',
  );
}
